# Usa una imagen base ligera de Java
FROM eclipse-temurin:17-jdk-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el .jar al contenedor
COPY carts.jar app.jar

# Exponer el puerto que usará Spring Boot
EXPOSE 8080

# Comando de arranque
ENTRYPOINT ["java", "-jar", "app.jar"]
